name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@v10.0.1
      with:
        python-version: "3.12"
        enable-cache: true
    - run: uv sync --locked --no-default-groups --group test
    - run: uv run coverage run -m pytest
    - run: uv run coverage report
    - run: uv run python -m xdoctest --modname=seaborn_image --command=all
