name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v10.0.1
      with:
        python-version: "3.12"
        enable-cache: true
    - run: uv sync --locked --no-default-groups --group test
    - run: uv run pytest
    - run: uv run python -m xdoctest --modname=seaborn_image --command=all
    - run: uv build
    - run: uv publish
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
